src/Entity/Entity.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EntityRepository")
 */
class Entity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Type;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Adress;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email()
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Directorname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)

     * @Assert\Regex(pattern="/^(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}$/")

     */
    private $Directorphone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email()
     */
    private $Directoremail;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File( maxSize = "5M")
     */
    private $Logo;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="10",minMessage="Description mini 10 caractères")
     * @Assert\NotBlank()
     */
    private $Descriptive;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Color;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $Linkmap;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Postalcity;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Facebook;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File( maxSize = "5M")
     */
    private $Logopage;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File( maxSize = "5M")
     */
    private $Photobandeau;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->Adress;
    }

    public function setAdress(string $Adress): self
    {
        $this->Adress = $Adress;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getDirectorName(): ?string
    {
        return $this->Directorname;
    }

    public function setDirectorName(string $Directorname): self
    {
        $this->Directorname = $Directorname;

        return $this;
    }

    public function getDirectorPhone(): ?string
    {
        return $this->Directorphone;
    }

    public function setDirectorPhone(string $Directorphone): self
    {
        $this->Directorphone = $Directorphone;

        return $this;
    }

    public function getDirectorEmail(): ?string
    {
        return $this->Directoremail;
    }

    public function setDirectorEmail(string $Directoremail): self
    {
        $this->Directoremail = $Directoremail;

        return $this;
    }

    public function getLogo()
    {
        return $this->Logo;
    }

    public function setLogo($Logo): self
    {
        $this->Logo = $Logo;

        return $this;
    }

    public function getDescriptive(): ?string
    {
        return $this->Descriptive;
    }

    public function setDescriptive(string $Descriptive): self
    {
        $this->Descriptive = $Descriptive;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->Color;
    }

    public function setColor(string $Color): self
    {
        $this->Color = $Color;

        return $this;
    }

    public function getLinkMap(): ?string
    {
        return $this->Linkmap;
    }

    public function setLinkMap(string $Linkmap): self
    {
        $this->Linkmap = $Linkmap;

        return $this;
    }

    public function getPostalCity(): ?string
    {
        return $this->Postalcity;
    }

    public function setPostalCity(string $Postalcity): self
    {
        $this->Postalcity = $Postalcity;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->Facebook;
    }

    public function setFacebook(string $Facebook): self
    {
        $this->Facebook = $Facebook;

        return $this;
    }

    public function getLogopage()
    {
        return $this->Logopage;
    }

    public function setLogopage($Logopage): self
    {
        $this->Logopage = $Logopage;

        return $this;
    }

    public function getPhotobandeau()
    {
        return $this->Photobandeau;
    }

    public function setPhotobandeau($Photobandeau): self
    {
        $this->Photobandeau = $Photobandeau;

        return $this;
    }
}

src/Form/InstructorType.php
<?php

namespace App\Form;

use App\Entity\Personnal;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InstructorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lastname', TextType::class, [
                'label' => 'Nom de l\'instructeur',
            ])
            ->add('firstname', TextType::class, [
                'label' => 'Prénom de l\'instructeur',
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email de l\'instructeur',
            ])
            ->add('phone', TextType::class, [
                'label' => 'Téléphone de l\'instructeur',
            ])
            ->add('address', TextType::class, [
                'label' => 'Adresse de l\'instructeur',
            ])
            ->add('role',ChoiceType::class, [
                'choices'  => [
                    'Instructeur' => 'Instructeur',],
                'label' => 'Role',
            ])
            ->add('grade',ChoiceType::class, [
                'choices'  => [
                    '1er Dan' => '1er Dan',
                    '2ème Dan' => '2ème Dan',
                    '3ème Dan' => '3ème Dan',
                    '4ème Dan' => '4ème Dan',
                    '5ème Dan' => '5ème Dan',
                    '6ème Dan' => '6ème Dan',
                    '7ème Dan' => '7ème Dan',
                    '8ème Dan' => '8ème Dan',
                    '9ème Dan' => '9ème Dan',
                    'Expert' => 'Expert',],
                'label' => 'Grade de l\'instructeur',
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description de l\'instructeur',
            ])
            ->add('link', TextType::class, [
                'label' => 'Lien Internet de l\'instructeur',
            ])
             ->add('photo',FileType::class, [
                'data_class' => null,
                 'label' => 'Photo de l\'instructeur',
             ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Personnal::class,
        ]);
    }
}

src/Controller/InstructorsController.php
<?php

namespace App\Controller;

use App\Repository\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\PersonnalRepository;
use App\Entity\Personnal;

class InstructorsController extends AbstractController
{
    /**
     * @Route("/instructors", name="instructors")
     * @param EntityRepository $entityRepository
     * @return Response
     */
    public function instructors(
        PersonnalRepository $personnalRepository,
        PersonnalRepository $instructors,
        EntityRepository $entityRepository
    ) {
        $repo = $this->getDoctrine()->getRepository(Personnal::class);
        $instructors = $repo->findInstructors();

        $entity = $entityRepository->findAll();

        return $this->render('instructors/instructors.html.twig', [
            'controller_name' => 'InstructorsController',
            'instructeur' => $instructors,
            'entitys' => $entity,
        ]);
    }
}

templates/instructors/instructors.html.twig
{% extends 'base.html.twig' %}



{% block body %}
    {% for entity in entitys %}
        <div class="instructors_jumbotron jumbotron jumbotron-fluid" style="background-image: url(../img/{{ entity.photobandeau }});">
            <div class="container">
                <h2 class="display-4" style="text-align: left;"><span>Nos instructeurs</span></h2>                
            </div>
        </div>
    {% endfor %}

    <!-- Photo by Timothy Eberly on Unsplash -->
    <!-- Cards Instructeurs-->
    <div class="container">
        {% if app.user %}
            <a href="{{ path('security_FormInstructor') }}" class="badge badge-pill badge-primary">
                <i class="fa fa-plus"> Ajouter un instructeur</i>
            </a>
        {% endif %}
        <div class="row my-5">
            {% for instructor in instructeur %}
                {% if instructor.role == 'Instructeur' %}
                    {% if not app.user %}
                        <div class="col-12 col-md-6 col-lg-4 mb-5">
                            <div class="card" style="width: 18rem;">
                                <img src="{{ "/img/"~ instructor.photo }}" class="card-img-top" alt="photo instructeur" >
                                <div class="card-body">
                                    <h5 class="card-title">{{ instructor.lastname }} {{ instructor.firstname }}</h5>
                                    <p class="card-text">{{ instructor.grade }}</p>
                                    <p class="card-text">{{ instructor.description }}</p>
                                    {% if instructor.link != "" %}
                                        <p class="card-text"><a class="instructor_link" target="_blank" href="{{ instructor.link }}">Site personnel</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="col-12 col-md-6 col-lg-4 mb-5">
                            <div class="card" style="width: 18rem;">
                                <img src="{{ "/img/"~ instructor.photo }}" class="card-img-top" alt="photo instructeur">
                                <div class="card-body">
                                    <h5 class="card-title">{{ instructor.lastname }} {{ instructor.firstname }}</h5>
                                    <p class="card-text">{{ instructor.grade }}</p>
                                    <p class="card-text">{{ instructor.description }}</p>
                                    {% if instructor.link != "" %}
                                        <p class="card-text"><a class="instructor_link" target="_blank" href="{{ instructor.link }}">Site personnel</a></p>
                                    {% endif %}
                                    <form class="d-inline" method="post"  action="{{ path('instructors_delete', {'id': instructor.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer {{instructor.role }},{{ instructor.lastname }} ?')">
                                        <input type="hidden" name="token" value="{{ csrf_token('delete') }}" />
                                        <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                    <a href="{{ path('security_FormInstructeurEdit',{'id':instructor.id}) }}" class="btn btn-sm btn-info">
                                        <i class="fa fa-pencil"></i>
                                    </a>

                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}