src/Entity/Entity.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EntityRepository")
 */
class Entity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Type;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Adress;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email()
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Directorname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)

     * @Assert\Regex(pattern="/^(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}$/")

     */
    private $Directorphone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email()
     */
    private $Directoremail;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File( maxSize = "5M")
     */
    private $Logo;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="10",minMessage="Description mini 10 caractères")
     * @Assert\NotBlank()
     */
    private $Descriptive;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Color;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $Linkmap;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Postalcity;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Facebook;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File( maxSize = "5M")
     */
    private $Logopage;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File( maxSize = "5M")
     */
    private $Photobandeau;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->Adress;
    }

    public function setAdress(string $Adress): self
    {
        $this->Adress = $Adress;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getDirectorName(): ?string
    {
        return $this->Directorname;
    }

    public function setDirectorName(string $Directorname): self
    {
        $this->Directorname = $Directorname;

        return $this;
    }

    public function getDirectorPhone(): ?string
    {
        return $this->Directorphone;
    }

    public function setDirectorPhone(string $Directorphone): self
    {
        $this->Directorphone = $Directorphone;

        return $this;
    }

    public function getDirectorEmail(): ?string
    {
        return $this->Directoremail;
    }

    public function setDirectorEmail(string $Directoremail): self
    {
        $this->Directoremail = $Directoremail;

        return $this;
    }

    public function getLogo()
    {
        return $this->Logo;
    }

    public function setLogo($Logo): self
    {
        $this->Logo = $Logo;

        return $this;
    }

    public function getDescriptive(): ?string
    {
        return $this->Descriptive;
    }

    public function setDescriptive(string $Descriptive): self
    {
        $this->Descriptive = $Descriptive;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->Color;
    }

    public function setColor(string $Color): self
    {
        $this->Color = $Color;

        return $this;
    }

    public function getLinkMap(): ?string
    {
        return $this->Linkmap;
    }

    public function setLinkMap(string $Linkmap): self
    {
        $this->Linkmap = $Linkmap;

        return $this;
    }

    public function getPostalCity(): ?string
    {
        return $this->Postalcity;
    }

    public function setPostalCity(string $Postalcity): self
    {
        $this->Postalcity = $Postalcity;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->Facebook;
    }

    public function setFacebook(string $Facebook): self
    {
        $this->Facebook = $Facebook;

        return $this;
    }

    public function getLogopage()
    {
        return $this->Logopage;
    }

    public function setLogopage($Logopage): self
    {
        $this->Logopage = $Logopage;

        return $this;
    }

    public function getPhotobandeau()
    {
        return $this->Photobandeau;
    }

    public function setPhotobandeau($Photobandeau): self
    {
        $this->Photobandeau = $Photobandeau;

        return $this;
    }
}

src/Controller/ClubController.php
<?php

namespace App\Controller;

use App\Entity\Personnal;
use App\Repository\DisciplinesRepository;
use App\Repository\EntityRepository;
use App\Repository\FilesRepository;
use App\Repository\PersonnalRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ClubController extends AbstractController
{
    /**
     * @Route("/club", name="club")
     * @param PersonnalRepository $personnalRepository
     * @param EntityRepository $entityRepository
     * @param DisciplinesRepository $disciplinesRepository
     * @param FilesRepository $filesRepository
     * @return Response
     */
    public function show(
        PersonnalRepository $personnalRepository,
        EntityRepository $entityRepository,
        DisciplinesRepository $disciplinesRepository
){
        $personnal = $personnalRepository->findAll();
        $entity = $entityRepository->findAll();
        $disciplines = $disciplinesRepository->findAll();
        return $this->render('club/club.html.twig', [
            'personnals' => $personnal,
            'entitys' => $entity,
            'discipliness' => $disciplines

        ]);
    }


}

templates/club/club.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% for entity in entitys %}
        <div class="example-wrapper club_description" style="background-image: url(../img/{{ entity.logopage }});">
            <section class="text-center">
                <div class="container">
                    <h1 class="jumbotron-heading">{{ entity.name }}</h1>
                    <p><i class="fa fa-home"></i> {{ entity.adress }} {{ entity.postalcity }}</p>
                    <p><i class="fa fa-envelope mr-2"></i>{{ entity.email }}</p>
                    <p class="mb-0">{{ entity.descriptive }}</p>
                </div>
            </section>
        </div>

        <div class="container">

            <h2 class="text-center my-5 club_h2" id="club_disciplines">Disciplines :</h2>
            {% if app.user %}
                <a href="{{ path('security_FormDisciplines') }}" class="badge badge-pill badge-primary">
                    <i class="fa fa-plus"> Ajouter une discipline</i>
                </a>                
            {% endif %}

            <div class="club_disciplines my-5">
                <div class="row">
                    {% for disciplines in discipliness %}
                        {% if not app.user %}
                            <div class="col-xl-6 col-sm-12 col-12 py-3 px-5">
                                <h3 class="text-center">{{ disciplines.name|upper }}</h3>
                                <p>{{ disciplines.description }}</p>
                            </div>
                        {% else %}
                            <div class="col-xl-6 col-sm-12 col-12 py-3 px-5">
                                <h3 class="text-center">{{ disciplines.name|upper }}
                                    <form class="d-inline" method="post" action="{{ path('disciplines_delete', {'id': disciplines.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer {{ disciplines.name }} ?')">
                                        <input type="hidden" name="token" value="{{ csrf_token('delete') }}" />
                                        <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                    <a href="{{ path('security_formDisciplinesEdit', {'id': disciplines.id}) }}" class="btn btn-sm btn-primary">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                </h3>
                                <p>{{ disciplines.description }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

        </div>

        <!--
        On teste si le mode admin est selectionné et on affiche le bouton ajouter
        -->
        
        <div class="container club_membres" id="club_bureau">

            <h2 class="text-center club_h2">Membres du bureau</h2>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-4 col-mb-5">
                        {% if app.user %}
                            <a href="{{ path('securityFormMember') }}" class="badge badge-pill badge-primary">
                                <i class="fa fa-plus"> Ajouter un membre du bureau</i>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="row my-5">
                <div class="col-12 col-md-6 col-lg-4 mb-5">
                    <div class="card mb-5">

                        {% for personnal in personnals %}
                            {% if  personnal.role == 'Président' %}
                                <img class="card-img-top" src="./img/{{ personnal.photo }}" alt="Président">
                                <div class="card-body">
                                    <h2 class="card-title club_role">{{ personnal.role }} :</h2>
                                    <h3 class="card-title"><a title="View Product">{{ personnal.firstname }} {{ personnal.lastname }}</a></h3>
                                    <p><i class="fa fa-phone mr-2"></i> {{ personnal.phone }}</p>
                                    <p><i class="fa fa-envelope mr-2"></i> {{ personnal.email }}</p>
                                </div>
                            {% endif %}

                            {% if app.user %}
                                {% if personnal.role == 'Président' %}
                                    <span>
                                        <form class="d-inline" method="post" action="{{ path('club_delete', {'id': personnal.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer {{personnal.role }} ?')">
                                            <input type="hidden" name="token" value="{{ csrf_token('delete') }}" />
                                            <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                        </form>
                                        <a href="{{ path('security_FormMemberEdit',{'id':personnal.id}) }}" class="btn btn-sm btn-primary">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                    </span>
                                {% endif %}

                            {% endif %}
                        {% endfor %}

                    </div><!-- /.card mb-5 -->
                </div>

                <div class="col-12 col-md-6 col-lg-4 mb-5">
                    <div class="card mb-5">

                        {% for personnal in personnals %}
                            {% if  personnal.role == 'Secrétaire' %}
                                <img class="card-img-top" src="./img/{{ personnal.photo }}" alt="Secrétaire">
                                <div class="card-body">
                                    <h2 class="card-title club_role">{{ personnal.role }} :</h2>
                                    <h3 class="card-title"><a title="View Product">{{ personnal.firstname }} {{ personnal.lastname }}</a></h3>
                                    <p><i class="fa fa-phone mr-2"></i> {{ personnal.phone }}</p>
                                    <p><i class="fa fa-envelope mr-2"></i> {{ personnal.email }}</p>
                                </div>
                            {% endif %}

                            {% if app.user %}
                                {% if personnal.role == 'Secrétaire' %}
                                    <span>
                                        <form class="d-inline" method="post" action="{{ path('club_delete', {'id': personnal.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer {{personnal.role }} ?')">
                                            <input type="hidden" name="token" value="{{ csrf_token('delete') }}" />
                                            <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                        </form>
                                        <a href="{{ path('security_FormMemberEdit',{'id':personnal.id}) }}" class="btn btn-sm btn-primary">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                    </span>
                                {% endif %}

                            {% endif %}
                        {% endfor %}

                    </div><!-- /.card mb-5 -->
                </div>

                <div class="col-12 col-md-6 col-lg-4 mb-5">
                    <div class="card mb-5">

                        {% for personnal in personnals %}
                            {% if  personnal.role == 'Trésorier' %}
                                <img class="card-img-top" src="./img/{{ personnal.photo }}" alt="Trésorier">
                                <div class="card-body">
                                    <h2 class="card-title club_role">{{ personnal.role }} :</h2>
                                    <h3 class="card-title"><a title="View Product">{{ personnal.firstname }} {{ personnal.lastname }}</a></h3>
                                    <p><i class="fa fa-phone mr-2"></i> {{ personnal.phone }}</p>
                                    <p><i class="fa fa-envelope mr-2"></i> {{ personnal.email }}</p>
                                </div>
                            {% endif %}

                            {% if app.user %}
                                {% if personnal.role == 'Trésorier' %}
                                    <span>
                                        <form class="d-inline" method="post" action="{{ path('club_delete', {'id': personnal.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer {{personnal.role }} ?')">
                                            <input type="hidden" name="token" value="{{ csrf_token('delete') }}" />
                                            <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                        </form>
                                        <a href="{{ path('security_FormMemberEdit',{'id':personnal.id}) }}" class="btn btn-sm btn-primary">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                    </span>
                                {% endif %}

                            {% endif %}
                        {% endfor %}

                    </div><!-- /.card mb-5 -->
                </div>
            </div><!-- /card-body -->
        </div><!-- /.card mb-5 -->

    {% endfor %}
{% endblock %}