src/Entity/Entity.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EntityRepository")
 */
class Entity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Type;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Adress;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email()
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Directorname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)

     * @Assert\Regex(pattern="/^(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}$/")

     */
    private $Directorphone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email()
     */
    private $Directoremail;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File( maxSize = "5M")
     */
    private $Logo;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="10",minMessage="Description mini 10 caractères")
     * @Assert\NotBlank()
     */
    private $Descriptive;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Color;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $Linkmap;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Postalcity;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Facebook;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File( maxSize = "5M")
     */
    private $Logopage;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File( maxSize = "5M")
     */
    private $Photobandeau;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->Adress;
    }

    public function setAdress(string $Adress): self
    {
        $this->Adress = $Adress;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getDirectorName(): ?string
    {
        return $this->Directorname;
    }

    public function setDirectorName(string $Directorname): self
    {
        $this->Directorname = $Directorname;

        return $this;
    }

    public function getDirectorPhone(): ?string
    {
        return $this->Directorphone;
    }

    public function setDirectorPhone(string $Directorphone): self
    {
        $this->Directorphone = $Directorphone;

        return $this;
    }

    public function getDirectorEmail(): ?string
    {
        return $this->Directoremail;
    }

    public function setDirectorEmail(string $Directoremail): self
    {
        $this->Directoremail = $Directoremail;

        return $this;
    }

    public function getLogo()
    {
        return $this->Logo;
    }

    public function setLogo($Logo): self
    {
        $this->Logo = $Logo;

        return $this;
    }

    public function getDescriptive(): ?string
    {
        return $this->Descriptive;
    }

    public function setDescriptive(string $Descriptive): self
    {
        $this->Descriptive = $Descriptive;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->Color;
    }

    public function setColor(string $Color): self
    {
        $this->Color = $Color;

        return $this;
    }

    public function getLinkMap(): ?string
    {
        return $this->Linkmap;
    }

    public function setLinkMap(string $Linkmap): self
    {
        $this->Linkmap = $Linkmap;

        return $this;
    }

    public function getPostalCity(): ?string
    {
        return $this->Postalcity;
    }

    public function setPostalCity(string $Postalcity): self
    {
        $this->Postalcity = $Postalcity;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->Facebook;
    }

    public function setFacebook(string $Facebook): self
    {
        $this->Facebook = $Facebook;

        return $this;
    }

    public function getLogopage()
    {
        return $this->Logopage;
    }

    public function setLogopage($Logopage): self
    {
        $this->Logopage = $Logopage;

        return $this;
    }

    public function getPhotobandeau()
    {
        return $this->Photobandeau;
    }

    public function setPhotobandeau($Photobandeau): self
    {
        $this->Photobandeau = $Photobandeau;

        return $this;
    }
}

src/Entity/Files.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FilesRepository")
 */
class Files
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\File( maxSize = "5M")
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $size;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Discipline;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getLink()
    {
        return $this->link;
    }

    public function setLink($link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getDiscipline(): ?string
    {
        return $this->Discipline;
    }

    public function setDiscipline(string $Discipline): self
    {
        $this->Discipline = $Discipline;

        return $this;
    }
}

src/Controller/DocumentController.php
<?php

namespace App\Controller;

use App\Repository\DisciplinesRepository;
use App\Repository\EntityRepository;
use App\Repository\FilesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DocumentController extends AbstractController
{
    /**
     * @Route("/document", name="document")
     * @param FilesRepository $filesRepository
     * @param EntityRepository $entityRepository
     * @return Response
     */
    public function show(
        FilesRepository $filesRepository,
        EntityRepository $entityRepository,
        DisciplinesRepository $disciplinesRepository
){
        $files = $filesRepository->findAll();
        $entity = $entityRepository->findAll();
        $disciplines = $disciplinesRepository->findAll();
        return $this->render('document/doc.html.twig',[
            'files' => $files,
            'entitys' => $entity,
            'discipliness' => $disciplines,
        ]);
    }
}

templates/document/doc.html.twig
{% extends 'base.html.twig' %}



{% block body %}
</br>
<h3 class="text-center club_h2">Documents à télécharger</h3>
    {% if app.user %}
        <a href="{{ path('security_FormFiles') }}" class="badge badge-pill badge-primary">
            <i class="fa fa-plus"> Ajouter un document</i>
        </a>
    {% endif %}
<h5 class="doc_download my-5 mb-5" style="text-align: center">Vous pouvez télécharger les documents en cliquant sur les boutons "Aperçu pdf" :</h5>

<div class="container" style="text-align: center" >
        <div class="row">
            {% for disciplines in discipliness %}
                {% if not app.user %}
                    <div class="col-xl-6 col-sm-12 col-12 py-3 px-5">
                        <h3 class="text-center">{{ disciplines.name|upper }}</h3></br>

                        {% for file in files %}
                            {% if file.discipline == disciplines.name %}
                                <h6><i class="fa fa-file-pdf-o mr-2"></i> <a class="doc_file" target="_blank">{{ file.link }}</a></br>
                                <p class="doc_file2" >taille fichier : ({{ file.size }})</p></br> <p class="btn btn-dark view-pdf" id="buttonPdf" href="./docs/{{ file.link }}">Aperçu pdf</p></h6>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="col-xl-6 col-sm-12 col-12 py-3 px-12"> 
                        <h3 class="text-center">{{ disciplines.name|upper }}</h3>
                            {% for file in files %}
                                {% if file.discipline == disciplines.name %}
                                    <h6><i class="fa fa-file-pdf-o mr-2"></i> <a class="doc_file" target="_blank">{{ file.link }}</a></br>
                                        <p class="doc_file2">taille fichier : ({{ file.size }})</p></br> <p class="btn btn-dark view-pdf" id="buttonPdf" href="./docs/{{ file.link }}">Aperçu pdf</p>
                                        <form class="d-inline" method="post" action="{{ path('document_delete', {'id': file.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer {{file.title }} ?')">
                                            <input type="hidden" name="token" value="{{ csrf_token('delete') }}" />
                                            <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                        </form></h6>
                                {% endif %}
                            {% endfor %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
</div>
{% endblock %}